apiVersion: v1
kind: Service
metadata:
  name: react-fiap-service
  namespace: react
  labels:
    app: react-fiap-app
spec:
  type: LoadBalancer
  selector:
    app: react-fiap-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000