apiVersion: v1
kind: PersistentVolume
metadata:
  name: eks-sample-linux-nginx-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data