apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-sample-linux-nginx-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi